import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@progress/kendo-theme-bootstrap/dist/all.css";
import "@progress/kendo-theme-utils/dist/all.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Barkboard",
  description: "Generated by the team who brings you Bark!board",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
